services:
  php_apache:
    build:
      context: .
      dockerfile: Dockerfile-php-apache
    container_name: php_apache
    ports:
      - "8080:80"
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-1}
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-erp}
      DB_USER: ${DB_USER:-erp_user}
      DB_PASS: ${DB_PASS:-erp_pass}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}
      ASAAS_API_URL: ${ASAAS_API_URL:-https://api-sandbox.asaas.com/v3}
      ASAAS_ACCESS_TOKEN: ${ASAAS_ACCESS_TOKEN:-}
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erp_pass
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker:
    build:
      context: .
      dockerfile: Dockerfile-php-apache
    container_name: worker
    command: php bin/worker.php
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-1}
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-erp}
      DB_USER: ${DB_USER:-erp_user}
      DB_PASS: ${DB_PASS:-erp_pass}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}
      ASAAS_API_URL: ${ASAAS_API_URL:-https://api-sandbox.asaas.com/v3}
      ASAAS_ACCESS_TOKEN: ${ASAAS_ACCESS_TOKEN:-}
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - rabbitmq
    restart: unless-stopped
#  adminer:
#    image: adminer
#    container_name: adminer
#    ports:
#      - "8081:8080"
#    depends_on:
#      - mysql

